// Build step (no bundling): stamps VERSION into src/version.js and sw.js and writes the precache list.
// Usage: node tools/build.js [version]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const version = process.argv[2] || pkg.version;
fs.writeFileSync(path.join(root, 'src/version.js'), `// Generated by tools/build.js — do not edit by hand.\nexport const VERSION = '${version}';\n`);
const list = ['./', './index.html', './manifest.webmanifest'];
function walk(dir) {
  for (const e of fs.readdirSync(path.join(root, dir), { withFileTypes: true })) {
    const rel = `${dir}/${e.name}`;
    if (e.isDirectory()) walk(rel);
    else if (/\.(js|css|json|png|svg)$/.test(e.name) && !/LICENSE|README/.test(e.name)) list.push(`./${rel}`);
  }
}
walk('src'); walk('data'); walk('icons');
const swTemplate = fs.readFileSync(path.join(root, 'tools/sw.template.js'), 'utf8');
const sw = swTemplate.replace('__VERSION__', version).replace('self.__PRECACHE__ || []', JSON.stringify(list, null, 0));
fs.writeFileSync(path.join(root, 'sw.js'), sw);
console.log(`build: version ${version}, precache ${list.length} files`);
